# Generated by Django 4.2.20 on 2025-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_user_customurlslug_remove_user_url_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='castedvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
