# Generated by Django 4.2.20 on 2025-05-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('comments', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('comments', models.CharField(blank=True, default='No Comments', max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('add_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(blank=True, default='No reasons given', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoriesvotes', to='awards.categoriesmodel')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.companiesmodel')),
            ],
        ),
    ]
