# Generated by Django 4.2.20 on 2025-03-22 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0003_categoriesmodel_companiesmodel_votesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoriesvotes', to='awards.categoriesmodel'),
        ),
        migrations.AlterField(
            model_name='companiesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categores', to='awards.categoriesmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='votesmodel',
            unique_together={('voter', 'category')},
        ),
    ]
