# Generated by Django 4.2.20 on 2025-03-27 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0004_votesmodel_category_alter_companiesmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesmodel',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votersusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
