# Generated by Django 4.2.20 on 2025-03-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_companiesmodel_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categores', to='awards.categoriesmodel'),
        ),
    ]
