# Generated by Django 4.2.20 on 2025-03-27 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0008_alter_votesmodel_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companiesmodel',
            name='voter',
        ),
        migrations.AddField(
            model_name='companiesmodel',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='votersusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
