# Generated by Django 4.2.20 on 2025-03-28 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0009_remove_companiesmodel_voter_companiesmodel_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='votercategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
