# Generated by Django 4.2.20 on 2025-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_categoriesmodel_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
