# Generated by Django 4.2.20 on 2025-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_votesmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmodel',
            name='reasons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
