# Generated by Django 4.2.20 on 2025-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_votesmodel_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesmodel',
            name='reasons',
            field=models.CharField(blank=True, default='No reasons given', max_length=100, null=True),
        ),
    ]
