# Generated by Django 4.2.20 on 2025-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_alter_votesmodel_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesmodel',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
