# Generated by Django 4.2.20 on 2025-03-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0014_companiesmodel_add_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votesmodel',
            unique_together=set(),
        ),
    ]
