# Generated by Django 4.2.20 on 2025-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0016_alter_categoriesmodel_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesmodel',
            name='comments',
            field=models.CharField(blank=True, default='No Comments', max_length=30, null=True),
        ),
    ]
