# Generated by Django 4.2.20 on 2025-03-31 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0019_expensesmodel_sponsorsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesmodel',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companiesmodel',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='votersusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
